services:
  catalogdb: 
    image: mongo

  basketdb:
    image: redis:alpine
  
  pgadmin: 
    image: dpage/pgadmin4

  discountdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:

